---
title: "diffusion_comparison"
author: "Joseph E.S.Abrams"
date: "2024-01-26"
output: html_document
---
## loading packages
```{r}
#load packages
library(tidyverse)
library(gganimate)
library(lazyeval)
library(viridis)
library(ggExtra)
library(ggforce)
```
## load "correct" answer for EG with no cells need to load them in 1 at a time and pull out needed data then remove with rm
## sequece of time values for extracting the correct time step from each file
```{r}
#without Cells
exact_0p0001<- read.csv("../EGandGLY-noCells_0p0001/voxel_values_1.csv")
#dt_0p01<-seq(0,0.9,0.1)
solution_0p001<- read.csv("../EGandGLY-noCells_0p001/voxel_values_1.csv")
solution_0p01<- read.csv("../EGandGLY-noCells_0p01/voxel_values_1.csv")
solution_0p02<- read.csv("../EGandGLY-noCells_0p02/voxel_values_1.csv")
solution_0p05<- read.csv("../EGandGLY-noCells_0p05/voxel_values_1.csv")
solution_0p1<- read.csv("../EGandGLY-noCells_0p1/voxel_values_1.csv")
solution_0p2<- read.csv("../EGandGLY-noCells_0p2/voxel_values_1.csv")
solution_0p5<- read.csv("../EGandGLY-noCells_0p5/voxel_values_1.csv")
dt_0p01<-seq(0.0,10,1)

```

```{r}
#with cells
exact_0p0001 <- read.csv("../EGandGLY-withCells_0p0001/voxel_values_1.csv")
solution_0p001<- read.csv("../EGandGLY-withCells_0p001/voxel_values_1.csv")
solution_0p01<- read.csv("../EGandGLY-withCells_0p01/voxel_values_1.csv")
solution_0p02<- read.csv("../EGandGLY-withCells_0p02/voxel_values_1.csv")
solution_0p05<- read.csv("../EGandGLY-withCells_0p05/voxel_values_1.csv")
solution_0p1<- read.csv("../EGandGLY-withCells_0p1/voxel_values_1.csv")
solution_0p2<- read.csv("../EGandGLY-withCells_0p2/voxel_values_1.csv")
solution_0p5<- read.csv("../EGandGLY-withCells_0p5/voxel_values_1.csv")
dt_0p01<-seq(0.0,10,1)

```
## extract data points from giant files and recombine for analysis of large data set

```{r}
exact_0p0001 <- exact_0p0001 %>% select(current_time,concentration_GLY,voxel_id) %>% arrange(voxel_id,current_time)
solution_0p001<- solution_0p001 %>% select(current_time,concentration_GLY,voxel_id) %>% arrange(voxel_id,current_time)
solution_0p01<- solution_0p01 %>% select(current_time,concentration_GLY,voxel_id) %>% arrange(voxel_id,current_time)
solution_0p02<- solution_0p02 %>% select(current_time,concentration_GLY,voxel_id) %>% arrange(voxel_id,current_time)
solution_0p05<- solution_0p05 %>% select(current_time,concentration_GLY,voxel_id) %>% arrange(voxel_id,current_time)
solution_0p1<- solution_0p1 %>% select(current_time,concentration_GLY,voxel_id) %>% arrange(voxel_id,current_time)
solution_0p2<- solution_0p2 %>% select(current_time,concentration_GLY,voxel_id) %>% arrange(voxel_id,current_time)
solution_0p5<- solution_0p5 %>% select(current_time,concentration_GLY,voxel_id) %>% arrange(voxel_id,current_time)
#acc_voxels_0p01_total <- acc_voxels_current
#unique(acc_voxels_0p01_1$current_time)
test_difference <- abs(exact_0p0001$concentration_GLY - solution_0p001$concentration_GLY)
max(test_difference)
```

### error in 0.001
```{r}
err0p001 <- seq(1,11)
comparison <- seq(1,64000)

for (j in 1:length(dt_0p01))
{
  exact_select <- exact_0p0001 %>% filter(current_time==dt_0p01[j])
  solution_0p001_select <- solution_0p001 %>% filter(current_time==dt_0p01[j])
  for(i in 1:64000)
    {
      x<-exact_select[i,2]
      y<-solution_0p001_select[i,2]
      n <- abs(x-y)
      comparison[i] <-n
    }
    m_val <- max(comparison)
    err0p001[j] <- log(m_val)
}

```

### error in 0.01
```{r}
err0p01 <- seq(1,11)
comparison <- seq(1,64000)

for (j in 1:length(dt_0p01))
{
  exact_select <- exact_0p0001 %>% filter(current_time==dt_0p01[j])
  solution_0p01_select <- solution_0p01 %>% filter(current_time==dt_0p01[j])
  for(i in 1:64000)
    {
      x<-exact_select[i,2]
      y<-solution_0p01_select[i,2]
      n <- abs(x-y)
      comparison[i] <-n
    }
    m_val <- max(comparison)
    err0p01[j] <- log(m_val)
}

```


### error in 0.02
```{r}
err0p02 <- seq(1,11)
comparison <- seq(1,64000)

for (j in 1:length(dt_0p01))
{
  exact_select <- exact_0p0001 %>% filter(current_time==dt_0p01[j])
  solution_0p02_select <- solution_0p02 %>% filter(current_time==dt_0p01[j])
  for(i in 1:64000)
    {
      x<-exact_select[i,2]
      y<-solution_0p02_select[i,2]
      n <- abs(x-y)
      comparison[i] <-n
    }
    m_val <- max(comparison)
    err0p02[j] <- log(m_val)
}

```

### error in 0.05
```{r}
err0p05 <- seq(1,11)
comparison <- seq(1,64000)

for (j in 1:length(dt_0p01))
{
  exact_select <- exact_0p0001 %>% filter(current_time==dt_0p01[j])
  solution_0p05_select <- solution_0p05 %>% filter(current_time==dt_0p01[j])
  for(i in 1:64000)
    {
      x<-exact_select[i,2]
      y<-solution_0p05_select[i,2]
      n <- abs(x-y)
      comparison[i] <-n
    }
    m_val <- max(comparison)
    err0p05[j] <- log(m_val)
}

```


### error in 0.1
```{r}
err0p1 <- seq(1,11)
comparison <- seq(1,64000)

for (j in 1:length(dt_0p01))
{
  exact_select <- exact_0p0001 %>% filter(current_time==dt_0p01[j])
  solution_0p1_select <- solution_0p1 %>% filter(current_time==dt_0p01[j])
  for(i in 1:64000)
    {
      x<-exact_select[i,2]
      y<-solution_0p1_select[i,2]
      n <- abs(x-y)
      comparison[i] <-n
    }
    m_val <- max(comparison)
    err0p1[j] <- log(m_val)
}

```

### error in 0.2
```{r}
err0p2 <- seq(1,11)
comparison <- seq(1,64000)

for (j in 1:length(dt_0p01))
{
  exact_select <- exact_0p0001 %>% filter(current_time==dt_0p01[j])
  solution_0p2_select <- solution_0p2 %>% filter(current_time==dt_0p01[j])
  for(i in 1:64000)
    {
      x<-exact_select[i,2]
      y<-solution_0p2_select[i,2]
      n <- abs(x-y)
      comparison[i] <-n
    }
    m_val <- max(comparison)
    err0p2[j] <- log(m_val)
}

```
### error in 0.5
```{r}
err0p5 <- seq(1,11)
comparison <- seq(1,64000)

for (j in 1:length(dt_0p01))
{
  exact_select <- exact_0p0001 %>% filter(current_time==dt_0p01[j])
  solution_0p5_select <- solution_0p5 %>% filter(current_time==dt_0p01[j])
  for(i in 1:64000)
    {
      x<-exact_select[i,2]
      y<-solution_0p5_select[i,2]
      n <- abs(x-y)
      comparison[i] <-n
    }
    m_val <- max(comparison)
    err0p5[j] <- log(m_val)
}

```



```{r}
dt_list <- c(0.01,0.02,0.05,0.1,0.2,0.5)
log_dt <- seq(1,6)
for(i in 1:6)
{
  print(i)
  log_dt[i]=log(dt_list[i])
}
time_in_sec<-dt_0p01
loglog<-tibble(time_in_sec,err0p01,err0p02,err0p05,err0p1,err0p2,err0p5)
#loglog<-t(loglog)
loglog<- loglog %>% mutate(log_01=log_dt[1],log_02=log_dt[2],log_05=log_dt[3],log_1=log_dt[4],log_2=log_dt[5],log_5=log_dt[6])
r0 <- t(time_in_sec)
r1 <- t(err0p01)
r2 <- t(err0p02)
r3 <- t(err0p05)
r4 <- t(err0p1)
r5 <- t(err0p2)
r6 <- t(err0p5)
r7 <- t(loglog$log_01)
c_time_name <- c("t0","t1","t2","t3","t4","t5","t6","t7","t8","t9","t10","log_dt")
piv_loglog <- rbind.data.frame(err0p01,err0p02,err0p05,err0p1,err0p2,err0p5)
piv_loglog <- cbind(piv_loglog,log_dt)
colnames(piv_loglog) <- c_time_name

```

```{r}
log_log_plot_0<-ggplot(piv_loglog,aes(x=t0,y=log_dt))+geom_line(color="red",show.legend = TRUE) + geom_line(aes(x=t1, y=log_dt), color="blue", show.legend = TRUE) + geom_line(aes(x=t2, y=log_dt), color="green", show.legend = TRUE)+ geom_line(aes(x=t3, y=log_dt),color="purple", show.legend = TRUE)+ geom_line(aes(x=t4, y=log_dt),color="orange", show.legend = TRUE)+geom_line(aes(x=t5,y=log_dt), color="brown",show.legend = TRUE)+labs(x='log(dt)',y='log(Err)', color="At Time:")+geom_line(aes(color=row.names(piv_loglog)))+scale_color_manual(labels=c("0 sec", "1 sec", "2 sec", "3 sec", "4 sec", "5 sec"), values=c("red","blue","green","purple","orange","brown","black"))
log_log_plot_0
ggsave("EGandGLY_GLY_diffusion_withCells.png")
```