name: Tests MacOSX

on:
  push:
  pull_request:
    
jobs:
  build_virus_macrophage:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run : brew install gcc@10

    - name: ovarian_follicle
    - run: 
        make
        ./ovarian_follicle
